### ISSUE TITLE
2.1.x beta - backup pukes and reports successful at same time

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/openrepeater#61]
coming from a fresh install on a zero W, no controller installed but set for a ICS-1x board in the wizard.

immediately went to perform a back-up to share with developers, and got the following page

![image](https://user-images.githubusercontent.com/10390925/52510250-16e73380-2bb0-11e9-842a-3bc54f2a0f8a.png)

**Comment by abcrawford** [comment]
This is caused by not having a sound device present. You can create the alsamixer file if now sound card exists. Then the error was occurring when the backup class was trying to add a non-existent file into the archive. I've added a check to see if the file exists before trying to add it to the archive. Backup should not work without sound hardware attached.
