### ISSUE TITLE
default login still present for use pi

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/openrepeater#71]
The pi user password needs updated or blocked so it will reduce the risk of hacking when hooked to an outside network

**Comment by abcrawford** [comment]
I believe this may have caused and issue in the past. I think I disabled it in a past image, but I cannot remember what the issue was. I think in the setup guide I emphasis it's the end users responsibility to secure the Pi. Maybe we can add suggestions to a KB article. We can test with it disabled to make sure. Maybe add to the build script. Which would be unrelated to the "openrepeater" repo.

**Comment by Dloranger** [comment]
I would suggest just making it match the root password so its not the
default raspbian password at least

**Comment by abcrawford** [comment]
Maybe we can experiment with commands for the script. Probably better to move this issue over there.
